language: node_js
node_js:
    - 10
branches: master

script:
    - echo airalab.org > /CNAME

before_deploy:
    - npm install --global @gridsome/cli
    - npm ci
    - gridsome build

deploy:
    provider: pages
    token: $GH_TOKEN
    cleanup: false
    keep_history: true
    local_dir: dist
    edge: true
    on:
        branch: master
